"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Base
BASE_DIR = Path(__file__).resolve().parent.parent

# Cargar .env UNA sola vez con ruta explícita
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!4%u_foyr@+%cxp&xzzvo&o3er#$lo^sx92v8c_gazsjs6a-yr'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.getenv('DEBUG')
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'


#ALLOWED_HOSTS = ['192.168.1.5']
ALLOWED_HOSTS = ['192.168.1.5', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros
    'drf_yasg',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Apps de proyecto
    'categorias',         
    'ejercicios',         
    'contacto',
    'seguridad',
    'ejercicios_helper',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# ESTOS CODIGOS SON PARA CORS QUE PERMITEN EL ACCESO DESDE CUALQUIER ORIGEN
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    'http://192.168.1.5:5173',
]
CORS_ORIGIN_REGEX_WHITELIST = [
    r'^http://192\.168\.1\.5:5173$',
]

CSRF_TRUSTED_ORIGINS = [
    'http://192.168.1.5:8000',
    'http://192.168.1.5:5173',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]


SWAGGER_SETTINGS = {
    'VALIDATOR_URL': None,

    'DEFAULT_MODEL_RENDERING': 'example',

    'USE_SESSION_AUTH': False,
}


ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DATABASE_BD'),           
        'USER': os.getenv('DATABASE_USER'),       
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),  
        'HOST': os.getenv('DATABASE_SERVER'),          
        'PORT': os.getenv('DATABASE_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'autocommit': True
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True

USE_L10N = True 

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# --- Static & Media ---
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (archivos subidos)
MEDIA_ROOT = os.path.join(BASE_DIR, "upload")
MEDIA_URL = "/upload/"

# (Opcional) permisos por defecto de archivos subidos
FILE_UPLOAD_PERMISSIONS = 0o644

# ===== Email (Mailtrap sandbox) =====
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
# ====================================            